### ISSUE TITLE
Server rendering: TypeError: Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by sahat** [skratchdot/react-bootstrap-daterangepicker#14]
Since this library depends on jQuery it will throw `TypeError: Cannot read property 'document' of undefined` when working with sever-rendered React, i.e.  `React.renderToString()`

Any suggestions for a workaround solution?

**Comment by sahat** [comment]
Full stack trace:

```js
TypeError: Cannot read property 'document' of undefined
    at arr (/Users/sahat/Developer/dashboard/node_modules/react-bootstrap-daterangepicker/node_modules/jquery/dist/jquery.js:29:6)
    at Object.<anonymous> (/Users/sahat/Developer/dashboard/node_modules/react-bootstrap-daterangepicker/node_modules/jquery/dist/jquery.js:38:60)
    at Module._compile (module.js:460:26)
    at normalLoader (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:125:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:138:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/sahat/Developer/dashboard/node_modules/react-bootstrap-daterangepicker/lib/index.js:9:9)
```

**Comment by skratchdot** [comment]
Good question.  I haven't done much w/ the server side rendering aspects of React, but I have a few thoughts.  My first idea was to try something like Zepto (or a lightweight jQuery alternative) suggested here: https://github.com/skratchdot/react-bootstrap-daterangepicker/issues/12 - but that won't fix the source library that I am wrapping (see: https://github.com/skratchdot/react-bootstrap-daterangepicker/blob/212540f468788ecb0349b9aef68f711d5c8e2266/lib/daterangepicker.js#L604).  So if we went that route, I'd need to either:
1) add a build step to "fix" the source library
2) get changes pushed to the upstream source library
3) re-write/port the source library so it doesn't use jQuery, etc

Option 3 would be nice, but I'd lose all the changes being made upstream, so it would probably be a headache.

Another option for you: is there a state variable you can add, that only turns on when the "client-side" is active? Something like: `if (clientSideActive) {/*render <DateRangePicker />*/}?  Then you could only render the daterangepicker on the client side (not on the server).  That's only a quickfix.  Longterm solution would be to do an actual port of the source library, and get rid of the jQuery dependencies, etc.  I haven't looked at the React docs in a while to see if there's a way to do the "clientSideActive" thing...

**Comment by demiurg** [comment]
I'm getting a related (jquery server side rendering) error:
```/home/pavel/code/cyanomap/node_modules/react-bootstrap-daterangepicker/lib/daterangepicker.js:1339
    $.fn.daterangepicker = function (options, cb) {
                         ^
TypeError: Cannot set property 'daterangepicker' of undefined
    at /home/pavel/code/cyanomap/node_modules/react-bootstrap-daterangepicker/lib/daterangepicker.js:1339:26
    at DateRangePicker.parentEl (/home/pavel/code/cyanomap/node_modules/react-bootstrap-daterangepicker/lib/daterangepicker.js:26:5)
```
I was going to attempt step 3 until I read the part about upstream, which is a valid point.

**Comment by kawing-chiu** [comment]
+1. The same issue here.

**Comment by joshhornby** [comment]
A hacky way to fix this is something like

```
render() {
    let date;

    if(typeof window === 'undefined') {
      date = (<div></div>);
    } else {
      var DateRangePicker = require('react-bootstrap-daterangepicker');
      date = (<DateRangePicker startDate="1/1/2014" endDate="3/1/2014">
                <div>Click Me To Open Picker!</div>
            </DateRangePicker>);
    }

    return (
      <div>
        {date}
      </div>
    );
  }
```

But with this hack in place it seems it renders in a strange way. Guessing this is because of jQuery?

**Comment by ferenax** [comment]
@joshhornby I used your technique to get through that nasty error.

```javascript
$.fn.daterangepicker = function (options, cb) {
                         ^
TypeError: Cannot set property 'daterangepicker' of undefined
```

However, I am now getting the following error : 

```javascript
Warning: Only functions or strings can be mounted as React components.
/Volumes/DATA/Projects/deeplinq/node_modules/react/lib/ReactDefaultInjection.js:53
    tagName: type.toUpperCase(),
                 ^
TypeError: Cannot read property 'toUpperCase' of undefined
```

Seems it never ends ? any idea about this one ?

**Comment by joshhornby** [comment]
@ferenax Did you find a fix for this?

@skratchdot What with the talk over on https://github.com/skratchdot/react-bootstrap-daterangepicker/issues/36 about the big breaking changes maybe this can be pushed up the priority list as well?

**Comment by peter-mouland** [comment]
I have submitted a PR to the owner of `bootstrap-daterangepicker` https://github.com/dangrossman/bootstrap-daterangepicker/pull/816

If this gets accepted, then this issue will be sorted...

**Comment by peter-mouland** [comment]
@skratchdot The DateRangePicker merged my PR which stops the plugin from crashing when trying to render server-side.  If you update to `v2.0.12` you can close this issue!

**Comment by peter-mouland** [comment]
sorry - I was too eager, we also need to wait for https://github.com/dangrossman/bootstrap-daterangepicker/pull/817 then we're good to go!

**Comment by ThrowsException** [comment]
@kawing-chiu I get the same error. using babel and webpack. strange behavior is that in npm3 everything works fine. when using npm2 it breaks with the same error you're getting.

**Comment by skratchdot** [comment]
closing this due to inactivity. please re-open if this is still an issue in v6.0.0 or greater
