### ISSUE TITLE
Deprecation warning: moment construction falls back to js Date

### ISSUE THREAD

**Issue by xinghengwang** [skratchdot/react-bootstrap-daterangepicker#77]
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Arguments: [object Object]
Error
    at Function.createFromInputFallback (http://localhost:3001/dist/main-a211bc16e0db174aed08.js:123422:106)
    at configFromInput (http://localhost:3001/dist/main-a211bc16e0db174aed08.js:124838:33)
    at prepareConfig (http://localhost:3001/dist/main-a211bc16e0db174aed08.js:124809:14)
    at createFromConfig (http://localhost:3001/dist/main-a211bc16e0db174aed08.js:124776:45)
    at createLocalOrUTC (http://localhost:3001/dist/main-a211bc16e0db174aed08.js:124858:17)
    at local__createLocal (http://localhost:3001/dist/main-a211bc16e0db174aed08.js:124862:17)
    at Moment.isAfter (http://localhost:3001/dist/main-a211bc16e0db174aed08.js:125360:53)
    at DateRangePicker.renderTimePicker (http://localhost:3001/dist/main-a211bc16e0db174aed08.js:175502:35)
    at DateRangePicker.updateView (http://localhost:3001/dist/main-a211bc16e0db174aed08.js:175158:23)
    at DateRangePicker.show (http://localhost:3001/dist/main-a211bc16e0db174aed08.js:175724:19)

**Comment by skratchdot** [comment]
closing this due to inactivity. please re-open if this is still an issue in v6.0.0 or greater
